const WA_NUMBER="971565702284",EMAIL="appletrade.ae@gmail.com",SOCIAL_HANDLE="appletrade.ae";
/* Keep true until AppleTrade.ae has the appropriate approvals/licence and is ready to accept commercial requests. */
const DEMO_MODE=true;
function money(n){return Math.round(n).toLocaleString("en-AE")}
function waLink(msg){return "https://wa.me/"+WA_NUMBER+"?text="+encodeURIComponent(msg)}
function toggleMenu(){document.querySelector(".navlinks")?.classList.toggle("open")}
function header(active){return `${DEMO_MODE?'<div class="dev-banner">DEVELOPMENT / TEST WEBSITE — Commercial services are not yet active. No purchases, sales, payments or binding trade-in requests are being accepted.</div>':''}<nav class="nav"><div class="container nav-in"><a class="brand" href="index.html"><span class="brand-mark">AT</span><span>AppleTrade<span>.ae</span></span></a><button class="menu" onclick="toggleMenu()">☰</button><div class="navlinks"><a class="${active==='home'?'active':''}" href="index.html">Home</a><a class="${active==='sell'?'active':''}" href="sell.html">Sell Demo</a><a class="${active==='trade'?'active':''}" href="trade.html">Trade-In Demo</a><a class="${active==='devices'?'active':''}" href="devices.html">Models & Estimates</a><a href="contact.html">Contact</a>${DEMO_MODE?'<span class="nav-cta demo-pill">DEMO MODE</span>':`<a class="nav-cta" href="https://wa.me/${WA_NUMBER}" target="_blank">WhatsApp</a>`}</div></div></nav>`}
function footer(){return `<footer class="footer"><div class="container footer-grid"><div><strong>AppleTrade.ae</strong><p>${DEMO_MODE?'Website concept currently under development. Commercial buying, selling and trade-in services are not active.':'Independent UAE device buying and trade-in service. Estimates are based on model, configuration and condition.'}</p><div class="social"><a href="https://www.facebook.com/${SOCIAL_HANDLE}" target="_blank">Facebook</a><a href="https://www.instagram.com/${SOCIAL_HANDLE}" target="_blank">Instagram</a><a href="https://www.tiktok.com/@${SOCIAL_HANDLE}" target="_blank">TikTok</a></div></div><div><strong>Quick links</strong><p><a href="sell.html">Sell estimate demo</a><br><a href="trade.html">Trade-In estimate demo</a><br><a href="devices.html">Models & estimates</a></p></div><div><strong>Project contact</strong><p>Email: ${EMAIL}<br>UAE</p></div></div><div class="container legal-footer"><p><b>Development notice:</b> No online purchases, sales, payments or binding trade-in requests are currently accepted. Prices and valuations shown are demonstration estimates only. Commercial services will be activated only when the project is ready and applicable requirements have been addressed.</p><p>AppleTrade.ae is an independent project and is not affiliated with, endorsed by, or sponsored by Apple Inc. Apple and Apple product names are trademarks of their respective owners.</p><p>© ${new Date().getFullYear()} AppleTrade.ae.</p></div></footer>${DEMO_MODE?'':'<a class="float-wa" href="https://wa.me/'+WA_NUMBER+'" target="_blank" aria-label="WhatsApp">⌕</a>'}`}
function enablePWA(){
 if(!document.querySelector('link[rel="manifest"]')){let m=document.createElement('link');m.rel='manifest';m.href='manifest.webmanifest';document.head.appendChild(m)}
 let theme=document.createElement('meta');theme.name='theme-color';theme.content='#05080d';document.head.appendChild(theme);
 let cap=document.createElement('meta');cap.name='apple-mobile-web-app-capable';cap.content='yes';document.head.appendChild(cap);
 let title=document.createElement('meta');title.name='apple-mobile-web-app-title';title.content='AppleTrade';document.head.appendChild(title);
 let icon=document.createElement('link');icon.rel='apple-touch-icon';icon.href='app-icon.svg';document.head.appendChild(icon);
 if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
}
function shell(active,title,content){document.body.innerHTML=header(active)+content+footer();document.title=title;enablePWA()}
