/* AppleTrade.ae original product previews + demo estimate confirmation */
(function(){
const css=document.createElement('link');css.rel='stylesheet';css.href='enhancements.css';document.head.appendChild(css);
function model(){try{return selectedModel()}catch(e){return null}}
function safe(s){return String(s||'').replace(/[&<>"']/g,'')}
function finishColor(c){c=(c||'').toLowerCase();if(c.includes('burgundy')||c.includes('red'))return'#8b2635';if(c.includes('orange'))return'#e46f2b';if(c.includes('purple')||c.includes('lavender'))return'#9382b8';if(c.includes('blue')||c.includes('glacier'))return'#799bb8';if(c.includes('green')||c.includes('sage'))return'#7f9b88';if(c.includes('gold')||c.includes('starlight')||c.includes('desert'))return'#d0b58e';if(c.includes('white')||c.includes('silver'))return'#d9dde2';if(c.includes('pink')||c.includes('rose'))return'#d8a5ac';if(c.includes('natural'))return'#aaa397';if(c.includes('black')||c.includes('graphite')||c.includes('midnight')||c.includes('space gray'))return'#34383e';return'#778899'}
function originalSVG(m){const c=typeof cat!=='undefined'?cat:'iphone',name=safe(m&&m.name||'Device'),finish=finishColor(typeof pickedColor!=='undefined'?pickedColor:(m.colors&&m.colors[0]));let art='';if(c==='macbook'){art=`<rect x="245" y="115" width="410" height="265" rx="18" fill="${finish}"/><rect x="260" y="130" width="380" height="235" rx="10" fill="#07111e"/><rect x="180" y="390" width="540" height="25" rx="12" fill="${finish}"/><path d="M165 415h570c-25 34-545 34-570 0" fill="#737982"/>`}else if(c==='ipad'){art=`<rect x="280" y="75" width="340" height="480" rx="35" fill="${finish}"/><rect x="298" y="94" width="304" height="442" rx="24" fill="#07111e"/><circle cx="450" cy="86" r="5" fill="#111827"/>`}else if(c==='watch'){art=`<rect x="385" y="35" width="130" height="135" rx="35" fill="${finish}"/><rect x="350" y="145" width="200" height="280" rx="55" fill="${finish}"/><rect x="366" y="162" width="168" height="246" rx="42" fill="#07111e"/><circle cx="555" cy="230" r="13" fill="${finish}"/><rect x="385" y="400" width="130" height="210" rx="35" fill="${finish}"/>`}else{const pro=/pro/i.test(name),old=/iPhone (11|12|13)/.test(name)&&!/mini/.test(name);art=`<rect x="315" y="65" width="270" height="510" rx="48" fill="${finish}"/><rect x="328" y="78" width="244" height="484" rx="39" fill="#07111e"/><rect x="345" y="96" width="210" height="448" rx="30" fill="url(#screen)"/><rect x="405" y="88" width="90" height="22" rx="12" fill="#05080d"/><rect x="335" y="88" width="112" height="112" rx="27" fill="${finish}" opacity=".98"/>${pro?'<circle cx="365" cy="120" r="25" fill="#111827"/><circle cx="414" cy="120" r="25" fill="#111827"/><circle cx="389" cy="169" r="25" fill="#111827"/><circle cx="431" cy="165" r="8" fill="#dbeafe"/>':old?'<circle cx="368" cy="122" r="26" fill="#111827"/><circle cx="412" cy="164" r="26" fill="#111827"/>':'<circle cx="369" cy="122" r="26" fill="#111827"/><circle cx="413" cy="164" r="26" fill="#111827"/>'}`}
return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="650" viewBox="0 0 900 650"><defs><radialGradient id="bg"><stop stop-color="#1d3552"/><stop offset="1" stop-color="#070b12"/></radialGradient><linearGradient id="screen" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#2563eb"/><stop offset=".5" stop-color="#7c3aed"/><stop offset="1" stop-color="#111827"/></linearGradient></defs><rect width="900" height="650" rx="42" fill="url(#bg)"/>${art}<text x="450" y="618" text-anchor="middle" fill="#f8fafc" font-family="Arial" font-size="28" font-weight="700">${name}</text></svg>`)}`}
window.refreshProductPreview=function(){const m=model(),img=document.getElementById('selectedProductImage'),title=document.getElementById('selectedProductTitle');if(!img||!m)return;img.src=originalSVG(m);img.alt=m.name+' AppleTrade original preview';if(title)title.textContent=m.name};
function injectPreview(){const s=document.getElementById('model');if(!s||document.getElementById('productPreview'))return;const box=document.createElement('div');box.id='productPreview';box.className='product-preview';box.innerHTML='<div class="product-preview-media"><img id="selectedProductImage" alt="Selected device"></div><div><div class="eyebrow">APPLETRADE ORIGINAL PREVIEW</div><h3 id="selectedProductTitle"></h3><p>Illustrative preview created for AppleTrade.ae. It is not Apple marketing photography. Preview updates with the selected model and finish.</p></div>';s.closest('.field').insertAdjacentElement('afterend',box);refreshProductPreview()}
const oldUpdate=window.updateModel;window.updateModel=function(){const r=oldUpdate.apply(this,arguments);setTimeout(refreshProductPreview,0);return r};const oldPick=window.pickColor;window.pickColor=function(){const r=oldPick.apply(this,arguments);setTimeout(refreshProductPreview,0);return r};
function ensureModal(){if(document.getElementById('estimateModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="estimate-modal" id="estimateModal" aria-hidden="true"><div class="estimate-dialog" role="dialog" aria-modal="true"><button class="modal-x" onclick="closeEstimateModal()" aria-label="Close">×</button><div class="estimate-icon">i</div><div class="eyebrow">DEVELOPMENT / DEMO MODE</div><h2>Estimated Value Only</h2><p class="estimate-lead">This calculator is currently a <b>demonstration tool</b>. The displayed amount is not a guaranteed final price and no sale, purchase, payment or binding trade-in request is being accepted through this demo.</p><div class="inspection-pills"><span>Condition</span><span>Battery health</span><span>Screen</span><span>Cameras</span><span>Face ID / Touch ID</span><span>Parts history</span><span>Activation Lock</span></div><p class="estimate-small">When commercial services are activated, an exact offer would only be confirmed after physical inspection and diagnostics.</p><button class="whatsapp modal-continue" id="estimateContinue">Close demo preview</button><button class="modal-back" onclick="closeEstimateModal()">Go back and review</button></div></div>`)}
window.closeEstimateModal=function(){const m=document.getElementById('estimateModal');if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}};
window.sendQuote=function(){ensureModal();const m=document.getElementById('estimateModal');m.classList.add('open');m.setAttribute('aria-hidden','false');document.getElementById('estimateContinue').onclick=closeEstimateModal};
function addPersistentNotice(){const q=document.querySelector('.quote');if(!q||document.getElementById('estimatePersistent'))return;const n=document.createElement('div');n.id='estimatePersistent';n.className='estimate-persistent';n.innerHTML='<b>Demo estimate only</b><span>No transaction or trade-in request is being accepted. Future final prices will depend on physical inspection and diagnostics.</span>';const btn=q.querySelector('.whatsapp');if(btn){btn.textContent='Preview Estimated Quote • Demo Only';q.insertBefore(n,btn)}}
document.addEventListener('DOMContentLoaded',()=>{injectPreview();ensureModal();addPersistentNotice();refreshProductPreview()});setTimeout(()=>{injectPreview();ensureModal();addPersistentNotice();refreshProductPreview()},0);
})();