/* AppleTrade.ae model-aware original previews + demo estimate confirmation */
(function(){
const css=document.createElement('link');css.rel='stylesheet';css.href='enhancements.css?v=20261005-7';document.head.appendChild(css);
function model(){try{return selectedModel()}catch(e){return null}}
function safe(s){return String(s||'').replace(/[&<>"']/g,'')}
function finishColor(c){c=(c||'').toLowerCase();if(c.includes('burgundy')||c.includes('red'))return'#70283d';if(c.includes('orange'))return'#d06b38';if(c.includes('purple')||c.includes('lavender'))return'#8c80ba';if(c.includes('blue')||c.includes('glacier'))return'#91b7d2';if(c.includes('green')||c.includes('sage')||c.includes('teal'))return'#829b8c';if(c.includes('gold')||c.includes('starlight')||c.includes('desert'))return'#ccb88e';if(c.includes('white')||c.includes('silver'))return'#dfe3e6';if(c.includes('pink')||c.includes('rose'))return'#d9a8b1';if(c.includes('natural'))return'#aaa49a';if(c.includes('black')||c.includes('graphite')||c.includes('midnight')||c.includes('space gray'))return'#2d3138';return'#8794a3'}
function lens(cx,cy,r=40){return `<circle cx="${cx}" cy="${cy}" r="${r+7}" fill="#20252d"/><circle cx="${cx}" cy="${cy}" r="${r}" fill="#05070a"/><circle cx="${cx-8}" cy="${cy-9}" r="${Math.round(r*.35)}" fill="#172c48"/><circle cx="${cx-13}" cy="${cy-14}" r="${Math.round(r*.12)}" fill="#9bc9ff" opacity=".75"/>`}
function duoArt(finish){return `<g><g transform="translate(52 12) rotate(-5 390 310)"><rect x="145" y="82" width="278" height="470" rx="42" fill="${finish}" stroke="#f8fafc" stroke-opacity=".22" stroke-width="4"/><rect x="160" y="98" width="248" height="438" rx="31" fill="#070a0f"/><rect x="172" y="111" width="224" height="412" rx="24" fill="url(#screen2)"/><rect x="402" y="105" width="10" height="420" rx="5" fill="#171b22"/><rect x="416" y="74" width="335" height="486" rx="45" fill="#151a21" stroke="${finish}" stroke-width="8"/><rect x="431" y="91" width="305" height="451" rx="32" fill="url(#screen)"/><line x1="583" y1="96" x2="583" y2="536" stroke="#fff" stroke-opacity=".08"/><rect x="543" y="108" width="80" height="20" rx="12" fill="#030405"/><circle cx="583" cy="118" r="5" fill="#253348"/></g></g>`}
function iphoneArt(name,finish){if(/Duo/i.test(name))return duoArt(finish);const pro=/pro/i.test(name),se=/SE/.test(name),mini=/mini/i.test(name),single=/16e|17e/.test(name),modern=/iPhone (1[4-8])/.test(name);let cams='';if(pro){cams=`<rect x="190" y="92" width="210" height="205" rx="52" fill="${finish}" filter="url(#shadow)"/>${lens(250,151)}${lens(340,151)}${lens(250,242)}<circle cx="342" cy="236" r="13" fill="#efe1b4"/><circle cx="375" cy="240" r="9" fill="#111820"/>`}else if(single){cams=`<rect x="205" y="100" width="120" height="120" rx="38" fill="${finish}" filter="url(#shadow)"/>${lens(265,160,39)}<circle cx="348" cy="125" r="11" fill="#efe1b4"/>`}else{cams=`<rect x="195" y="94" width="172" height="188" rx="48" fill="${finish}" filter="url(#shadow)"/>${lens(245,145,38)}${lens(316,225,38)}<circle cx="332" cy="128" r="10" fill="#efe1b4"/>`}
const island=se?'':modern?'<rect x="609" y="88" width="90" height="24" rx="14" fill="#020305"/>':'<path d="M600 78h110v30c-18 12-92 12-110 0z" fill="#030406"/>';
const bw=mini?300:330;return `<g><g transform="rotate(-7 320 320)"><rect x="160" y="55" width="${bw}" height="540" rx="58" fill="${finish}" stroke="#fff" stroke-opacity=".22" stroke-width="4" filter="url(#shadow)"/>${cams}<circle cx="325" cy="455" r="38" fill="#fff" opacity=".035"/></g><g transform="rotate(6 650 320)"><rect x="515" y="50" width="${bw}" height="550" rx="58" fill="#15191f" stroke="${finish}" stroke-width="8" filter="url(#shadow)"/><rect x="528" y="64" width="${bw-26}" height="522" rx="47" fill="url(#screen)"/>${island}</g></g>`}
function ipadArt(finish){return `<g><rect x="260" y="50" width="380" height="550" rx="32" fill="${finish}" filter="url(#shadow)"/><rect x="273" y="63" width="354" height="524" rx="23" fill="#070a0f"/><rect x="285" y="76" width="330" height="498" rx="17" fill="url(#screen)"/><circle cx="450" cy="69" r="5" fill="#1b2635"/></g>`}
function macArt(finish,name){return `<g><rect x="198" y="85" width="505" height="335" rx="18" fill="${finish}" stroke="#fff" stroke-opacity=".22" stroke-width="3" filter="url(#shadow)"/><rect x="215" y="102" width="471" height="301" rx="9" fill="#080b10"/><rect x="228" y="115" width="445" height="275" rx="5" fill="url(#screen)"/><rect x="110" y="425" width="680" height="29" rx="11" fill="${finish}"/><path d="M108 454h684c-28 40-656 40-684 0" fill="#777e87"/><rect x="408" y="425" width="84" height="7" rx="4" fill="#484e56"/></g>`}
function watchArt(finish,name){const ultra=/Ultra/.test(name);return `<g><rect x="397" y="8" width="106" height="195" rx="43" fill="${finish}"/><rect x="${ultra?333:347}" y="143" width="${ultra?234:206}" height="315" rx="${ultra?51:64}" fill="${finish}" stroke="#fff" stroke-opacity=".25" stroke-width="4" filter="url(#shadow)"/><rect x="${ultra?348:361}" y="158" width="${ultra?204:178}" height="285" rx="${ultra?39:51}" fill="#06090d"/><circle cx="450" cy="300" r="90" fill="url(#screen)"/><circle cx="${ultra?582:565}" cy="236" r="16" fill="${finish}"/><rect x="397" y="421" width="106" height="220" rx="43" fill="${finish}"/></g>`}
function originalSVG(m){const c=typeof cat!=='undefined'?cat:'iphone',name=safe(m&&m.name||'Device'),finish=finishColor(typeof pickedColor!=='undefined'?pickedColor:(m.colors&&m.colors[0]));let art=c==='macbook'?macArt(finish,name):c==='ipad'?ipadArt(finish):c==='watch'?watchArt(finish,name):iphoneArt(name,finish);let label=c==='macbook'?'MACBOOK':c==='ipad'?'IPAD':c==='watch'?'APPLE WATCH':'IPHONE';return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="650" viewBox="0 0 900 650"><defs><radialGradient id="bg" cx="50%" cy="35%"><stop stop-color="#17283e"/><stop offset="1" stop-color="#05080d"/></radialGradient><linearGradient id="screen" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#1c80d5"/><stop offset=".35" stop-color="#4651c8"/><stop offset=".65" stop-color="#a14279"/><stop offset="1" stop-color="#0d1520"/></linearGradient><linearGradient id="screen2" x1="1" y1="0" x2="0" y2="1"><stop stop-color="#67b6e8"/><stop offset=".45" stop-color="#634dd8"/><stop offset="1" stop-color="#101725"/></linearGradient><filter id="shadow"><feDropShadow dx="0" dy="18" stdDeviation="18" flood-opacity=".55"/></filter></defs><rect width="900" height="650" rx="42" fill="url(#bg)"/><text x="42" y="52" fill="#7fb5ff" font-family="Arial" font-size="17" font-weight="700" letter-spacing="3">APPLETRADE ORIGINAL • ${label}</text>${art}<text x="450" y="627" text-anchor="middle" fill="#f8fafc" font-family="Arial" font-size="24" font-weight="700">${name}</text></svg>`)}`}
window.refreshProductPreview=function(){const m=model(),img=document.getElementById('selectedProductImage'),title=document.getElementById('selectedProductTitle');if(!img||!m)return;img.src=originalSVG(m);img.alt=m.name+' AppleTrade illustrative preview';if(title)title.textContent=m.name};
function injectPreview(){const s=document.getElementById('model');if(!s||document.getElementById('productPreview'))return;const box=document.createElement('div');box.id='productPreview';box.className='product-preview';box.innerHTML='<div class="product-preview-media"><img id="selectedProductImage" alt="Selected device"></div><div><div class="eyebrow">APPLETRADE ORIGINAL PREVIEW</div><h3 id="selectedProductTitle"></h3><p>Original illustrative preview created for AppleTrade.ae. It updates with the selected model and finish.</p></div>';s.closest('.field').insertAdjacentElement('afterend',box);refreshProductPreview()}
const oldUpdate=window.updateModel;window.updateModel=function(){const r=oldUpdate.apply(this,arguments);setTimeout(refreshProductPreview,0);return r};const oldPick=window.pickColor;window.pickColor=function(){const r=oldPick.apply(this,arguments);setTimeout(refreshProductPreview,0);return r};
function ensureModal(){if(document.getElementById('estimateModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="estimate-modal" id="estimateModal" aria-hidden="true"><div class="estimate-dialog" role="dialog" aria-modal="true"><button class="modal-x" onclick="closeEstimateModal()">×</button><div class="estimate-icon">i</div><div class="eyebrow">DEVELOPMENT / DEMO MODE</div><h2>Your estimate is not the final price</h2><p class="estimate-lead">The amount shown is a <b>non-binding demonstration estimate</b>. No sale, purchase, payment or trade-in request is being accepted through this development website.</p><div class="inspection-pills"><span>Physical condition</span><span>Battery health</span><span>Screen</span><span>Cameras</span><span>Face ID / Touch ID</span><span>Parts history</span><span>Activation Lock</span></div><p class="estimate-small">If commercial services are activated in the future, the exact price would only be discussed and confirmed after physical inspection and diagnostics of the actual device.</p><button class="whatsapp modal-continue" id="estimateContinue">I understand • Close preview</button></div></div>`)}
window.closeEstimateModal=function(){const m=document.getElementById('estimateModal');if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}};window.sendQuote=function(){ensureModal();const m=document.getElementById('estimateModal');m.classList.add('open');m.setAttribute('aria-hidden','false');document.getElementById('estimateContinue').onclick=closeEstimateModal};
function addPersistentNotice(){const q=document.querySelector('.quote');if(!q||document.getElementById('estimatePersistent'))return;const n=document.createElement('div');n.id='estimatePersistent';n.className='estimate-persistent';n.innerHTML='<b>Estimated value only</b><span>This is not the exact price you will receive. Any future final value would be discussed only after physical inspection and diagnostics.</span>';const btn=q.querySelector('.whatsapp');if(btn){btn.textContent='Review Estimate Notice • Demo Only';q.insertBefore(n,btn)}}
document.addEventListener('DOMContentLoaded',()=>{injectPreview();ensureModal();addPersistentNotice();refreshProductPreview()});setTimeout(()=>{injectPreview();ensureModal();addPersistentNotice();refreshProductPreview()},0);
})();