/* Real product-photo selector and explicit estimated-value confirmation. */
(function(){
  const css=document.createElement('link');css.rel='stylesheet';css.href='enhancements.css?v=20261006-1';document.head.appendChild(css);const photoCss=document.createElement('link');photoCss.href='product-photos.css?v=20261006-3';photoCss.rel='stylesheet';document.head.appendChild(photoCss);
  function selected(){try{return selectedModel()}catch(_){return null}} function category(){return typeof cat==='string'?cat:'iphone'} function selectedColour(){return typeof pickedColor==='string'?pickedColor:''}
  function updatePreviewDetails(m,colour){const title=document.getElementById('selectedProductTitle'),model=document.getElementById('selectedProductModel'),finish=document.getElementById('selectedProductColour'),description=document.getElementById('selectedProductDescription');if(title)title.textContent=m.name;if(model)model.textContent=m.name;if(finish)finish.textContent=colour||'—';if(description)description.textContent=colour?'Selected '+m.name+' in '+colour+'.':'Selected '+m.name+'.'}
  window.refreshProductPreview=function(){const m=selected(),img=document.getElementById('selectedProductImage');if(!m||!img)return;const colour=selectedColour();updatePreviewDetails(m,colour);setProductImage(img,m,category(),colour);};
  function injectPreview(){const select=document.getElementById('model');if(!select||document.getElementById('productPreview'))return;const box=document.createElement('section');box.id='productPreview';box.className='product-preview';box.innerHTML='<div class="product-preview-media"><img id="selectedProductImage" loading="eager" alt="Selected Apple device product photo"></div><div class="product-preview-copy"><div class="eyebrow">YOUR SELECTION</div><h3 id="selectedProductTitle"></h3><div class="product-preview-specs"><span><small>MODEL</small><b id="selectedProductModel"></b></span><span><small>COLOUR / FINISH</small><b id="selectedProductColour"></b></span></div><p id="selectedProductDescription"></p></div>';select.closest('.field').insertAdjacentElement('afterend',box);refreshProductPreview();}
  const oldUpdate=window.updateModel;window.updateModel=function(){const result=oldUpdate.apply(this,arguments);setTimeout(refreshProductPreview,0);return result;};const oldColor=window.pickColor;window.pickColor=function(){const result=oldColor.apply(this,arguments);setTimeout(refreshProductPreview,0);return result;};
  function disclaimer(){return 'Estimated Value Only — This is not a guaranteed final price. The exact price will be confirmed after physical inspection and diagnostics of the device, including condition, battery health, screen, cameras, Face ID/Touch ID, parts history and activation-lock status.'}
  function ensureModal(){if(document.getElementById('estimateModal'))return;document.body.insertAdjacentHTML('beforeend','<div class="estimate-modal" id="estimateModal" aria-hidden="true"><div class="estimate-dialog" role="dialog" aria-modal="true" aria-labelledby="estimateHeading"><button class="modal-x" type="button" aria-label="Close" onclick="closeEstimateModal()">×</button><div class="estimate-icon">i</div><div class="eyebrow">PLEASE REVIEW</div><h2 id="estimateHeading">Estimated Value Only</h2><p class="estimate-lead" id="estimateDisclaimer"></p><button class="whatsapp modal-continue" id="estimateContinue" type="button">I understand — continue to WhatsApp</button></div></div>');document.getElementById('estimateDisclaimer').textContent=disclaimer();}
  window.closeEstimateModal=function(){const modal=document.getElementById('estimateModal');if(modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}};
  function message(){const m=selected(),amount=document.getElementById('price')?.textContent||'—',kind=typeof mode==='string'&&mode==='trade'?'Trade-In':'Sell';return ['AppleTrade.ae '+kind+' enquiry','Device: '+(m?m.name:'Selected device'),'Estimated value: AED '+amount,'','Acknowledgement: '+disclaimer()].join('\n')}
  window.sendQuote=function(){if(window.quoteRejected){alert('Please remove Activation Lock / MDM / owner lock before continuing.');return}ensureModal();const modal=document.getElementById('estimateModal');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.getElementById('estimateContinue').onclick=function(){window.open(waLink(message()),'_blank','noopener');closeEstimateModal()}};
  function addPersistentNotice(){const quote=document.querySelector('.quote');if(!quote||document.getElementById('estimatePersistent'))return;const note=document.createElement('div');note.id='estimatePersistent';note.className='estimate-persistent';note.innerHTML='<b>Estimated Value Only</b><span>Not a guaranteed final price. Confirmation follows physical inspection and diagnostics.</span>';quote.insertBefore(note,quote.querySelector('.whatsapp'));const button=quote.querySelector('.whatsapp');if(button)button.textContent='Continue to WhatsApp'}
  document.addEventListener('DOMContentLoaded',()=>{injectPreview();ensureModal();addPersistentNotice();refreshProductPreview()});setTimeout(()=>{injectPreview();ensureModal();addPersistentNotice();refreshProductPreview()},0);
})();

